### ISSUE TITLE
USBX SSTD Question 

### ISSUE THREAD

**Issue by bournesup** [weblogix/hackintosh-dell-precision-3240-compact-opencore#11]
I notice there are SSDT-USBX.aml and SSDT-EC-USBX-DESKTOP.aml in the ACPI. Are they duplicated?

**Comment by bournesup** [comment]
Figured it out. It is for USB power issue.

**Comment by weblogix** [comment]
@bournesup It looks like you are right.

SSDT-EC-USBX
Fixes both the embedded controller and USB power, see Getting Started With ACPI Guide (opens new window)for more details.

Source: https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#acpi


SSDT-EC-USBX-DESKTOP
Fixing Embedded Controllers: By far the easiest way to fix your Embedded Controller is just downloading one of the files below:

For Skylake desktops and newer and AMD CPU based systems

https://dortania.github.io/Getting-Started-With-ACPI/Universal/ec-methods/prebuilt.html#wrapping-up
